import './globals.css';
import type { Metadata } from 'next';
import { GlobalStateProvider } from './context/GlobalStateProvider';

import { Lexend } from 'next/font/google'
 
const roboto = Lexend({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GlobalStateProvider>
        <body className={roboto.className}>
          This is Root Layouyt
          {children}
          </body>
      </GlobalStateProvider>
    </html>
  );
}
