import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { GlobalStateProvider } from './context/GlobalStateProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GlobalStateProvider>
        <body className={inter.className}>
          This is Root Layouyt
          {children}
          </body>
      </GlobalStateProvider>
    </html>
  );
}
