import "./globals.css";
import type { Metadata } from "next";

import { Lexend } from "next/font/google";

const roboto = Lexend({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <html lang="en">
    <body>
      
    {children}
    </body>
  </html>;
}
