import { TComponentB } from "@/app/components/activity/UpdatedServiceCard";

const imageURL = "/square.jpg";

export const dataArray: TComponentB[] = [
    {
      productType: "Tour",
      productName: "Safari Adventure",
      imageURL,
      dateOfBooking: "2024-11-01",
      additionalInfo: { location: "Dubai" },
      headerInfo: { status: "pending" },
      bottomInfo: { price: "AED 350" },
      actionButton: {
        action: "button",
        primaryButtonText: "Proceed",
        secondaryButtonText: "Cancel",
        handlePrimaryBtnClick: (e) => console.log("Booking proceeded"),
        handleSecondaryBtnClick: (e) => console.log("Booking cancelled"),
      },
    },
    {
      productType: "Tour",
      productName: "City Sightseeing",
      imageURL,
      dateOfBooking: { startDate: "2024-10-10", endDate: "2024-10-12" },
      additionalInfo: { location: "Abu Dhabi" },
      headerInfo: {
        action: "button",
        handleClick: (e) => console.log("Action button clicked"),
      },
      bottomInfo: { price: "AED 500" },
      actionButton: {
        applicableRPoints: 200,
        handleClick: (e) => console.log("Rayna points applied"),
      },
    },
    {
      productType: "Hotel",
      productName: "Beachfront Resort",
      imageURL,
      dateOfBooking: "2024-09-15",
      additionalInfo: { location: "Sharjah" },
      headerInfo: { status: "confirmed" },
      bottomInfo: {
        price: "AED 1200",
        numOfRoom: 1,
        nuOfDays: 3,
        numOfAdults: 2,
        numOfChildren: 0,
      },
      actionButton: {
        action: "button",
        primaryButtonText: "Confirm",
        secondaryButtonText: "Modify",
        handlePrimaryBtnClick: (e) => console.log("Hotel booking confirmed"),
        handleSecondaryBtnClick: (e) => console.log("Hotel booking modified"),
      },
    },
    {
      productType: "Hotel",
      productName: "Luxury Apartments",
      imageURL,
      dateOfBooking: { startDate: "2024-11-21", endDate: "2024-11-25" },
      additionalInfo: { location: "Ras Al Khaimah" },
      headerInfo: { status: "pending" },
      bottomInfo: {
        price: "AED 5000",
        numOfRoom: 2,
        nuOfDays: 5,
        numOfAdults: 4,
        numOfChildren: 2,
      },
      actionButton: {
        applicableRPoints: 400,
        handleClick: (e) => console.log("Points applied to apartment booking"),
      },
    },
    {
      productType: "Visa",
      productName: "Student Visa",
      imageURL,
      dateOfBooking: "2024-08-01",
      additionalInfo: { numWorkingDays: "5-10" },
      headerInfo: { status: "confirmed" },
      bottomInfo: {
        price: "AED 1000",
        visaType: "Student",
        numOfTraveller: 1,
        validity: 180,
      },
      actionButton: {
        action: "button",
        primaryButtonText: "Submit Visa",
        secondaryButtonText: "Cancel",
        handlePrimaryBtnClick: (e) =>
          console.log("Student visa application submitted"),
        handleSecondaryBtnClick: (e) => console.log("Visa application cancelled"),
      },
    },
    {
      productType: "Visa",
      productName: "Business Visa",
      imageURL,
      dateOfBooking: "2024-09-15",
      additionalInfo: { numWorkingDays: "3-5" },
      headerInfo: { status: "pending" },
      bottomInfo: {
        price: "AED 1500",
        visaType: "Business",
        numOfTraveller: 2,
        validity: 90,
      },
      actionButton: {
        action: "button",
        primaryButtonText: "Proceed with Visa",
        secondaryButtonText: "Cancel",
        handlePrimaryBtnClick: (e) =>
          console.log("Business visa application processed"),
        handleSecondaryBtnClick: (e) => console.log("Visa application cancelled"),
      },
    },
    {
      productType: "Tour",
      productName: "Mountain Hike",
      imageURL,
      dateOfBooking: { startDate: "2024-12-12", endDate: "2024-12-14" },
      additionalInfo: { location: "Hatta" },
      headerInfo: { status: "confirmed" },
      bottomInfo: { price: "AED 800" },
      actionButton: {
        applicableRPoints: 150,
        handleClick: (e) => console.log("Rayna points redeemed for hike"),
      },
    },
    {
      productType: "Hotel",
      productName: "Skyline Suites",
      imageURL,
      dateOfBooking: { startDate: "2024-10-01", endDate: "2024-10-05" },
      additionalInfo: { location: "Dubai Marina" },
      headerInfo: undefined,
      bottomInfo: {
        price: "AED 3200",
        numOfRoom: 3,
        nuOfDays: 4,
        numOfAdults: 6,
        numOfChildren: 0,
      },
      actionButton: {
        action: "button",
        primaryButtonText: "Confirm Stay",
        secondaryButtonText: "Modify Booking",
        handlePrimaryBtnClick: (e) => console.log("Stay confirmed"),
        handleSecondaryBtnClick: (e) => console.log("Booking modified"),
      },
    },
    {
      productType: "Visa",
      productName: "Tourist Visa",
      imageURL,
      dateOfBooking: "2024-10-22",
      additionalInfo: { numWorkingDays: "3-4" },
      headerInfo: { status: "pending" },
      bottomInfo: {
        price: "AED 500",
        visaType: "Tourist",
        numOfTraveller: 3,
        validity: 30,
      },
      actionButton: {
        applicableRPoints: 100,
        handleClick: (e) => console.log("Tourist visa points applied"),
      },
    },
    {
      productType: "Tour",
      productName: "Cultural Heritage Walk",
      imageURL,
      dateOfBooking: "2024-09-30",
      additionalInfo: { location: "Al Ain" },
      headerInfo: {
        action: "button",
        handleClick: (e) => console.log("Booking action triggered"),
      },
      bottomInfo: {
        price: "AED 400",
        transferType: "Private",
        numOfAdults: 2,
        numOfChildren: 1,
      },
      actionButton: {
        applicableRPoints: 50,
        appliedRPoints: 20,
        handleClick: (e) => console.log("Points used for cultural tour"),
      },
    },
    {
      productType: "Hotel",
      productName: "Desert Camp",
      imageURL,
      dateOfBooking: { startDate: "2024-11-10", endDate: "2024-11-12" },
      additionalInfo: { location: "Liwa Desert" },
      headerInfo: { status: "confirmed" },
      bottomInfo: {
        price: "AED 2500",
        numOfRoom: 2,
        nuOfDays: 3,
        numOfAdults: 4,
        numOfChildren: 0,
      },
      actionButton: {
        action: "button",
        primaryButtonText: "Confirm Stay",
        secondaryButtonText: "Cancel",
        handlePrimaryBtnClick: (e) =>
          console.log("Desert camp booking confirmed"),
        handleSecondaryBtnClick: (e) => console.log("Booking cancelled"),
      },
    },
    {
      productType: "Tour",
      productName: "Seaside Kayaking",
      imageURL,
      dateOfBooking: "2024-10-05",
      additionalInfo: { location: "Fujairah" },
      headerInfo: undefined,
      bottomInfo: {
        price: "AED 300",
        transferType: "Group",
        numOfAdults: 1,
        numOfChildren: 1,
      },
      actionButton: {
        action: "button",
        primaryButtonText: "Book Now",
        secondaryButtonText: "Cancel",
        handlePrimaryBtnClick: (e) => console.log("Kayaking booking confirmed"),
        handleSecondaryBtnClick: (e) => console.log("Booking cancelled"),
      },
    },
  ];